// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Y_Gem.Data;

#nullable disable

namespace Y_Gem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914001031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Y_Gem.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Y_Gem.Models.Admin", b =>
                {
                    b.HasBaseType("Y_Gem.Models.Users");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Y_Gem.Models.Coaches", b =>
                {
                    b.HasBaseType("Y_Gem.Models.Users");

                    b.Property<string>("coachSpecialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Coaches", (string)null);
                });

            modelBuilder.Entity("Y_Gem.Models.Members", b =>
                {
                    b.HasBaseType("Y_Gem.Models.Users");

                    b.Property<double>("Hight")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Y_Gem.Models.Staff", b =>
                {
                    b.HasBaseType("Y_Gem.Models.Users");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("Y_Gem.Models.Admin", b =>
                {
                    b.HasOne("Y_Gem.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("Y_Gem.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Y_Gem.Models.Coaches", b =>
                {
                    b.HasOne("Y_Gem.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("Y_Gem.Models.Coaches", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Y_Gem.Models.Members", b =>
                {
                    b.HasOne("Y_Gem.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("Y_Gem.Models.Members", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Y_Gem.Models.Staff", b =>
                {
                    b.HasOne("Y_Gem.Models.Users", null)
                        .WithOne()
                        .HasForeignKey("Y_Gem.Models.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
